### ISSUE TITLE
Missing global namespace for class 'Exception' causing 'Class not found' exception

### ISSUE THREAD

**Issue by rdk01** [KyranRana/cloudflare-bypass#103]
Probably, a typo, but classes always resolve to the current namespace, so we need to use fully qualified name here:

https://github.com/KyranRana/cloudflare-bypass/blob/5fde39d4c3b9e4a9670747bacc9e18663818208e/src/CloudflareBypass/CFBypasser.php#L182

**Comment by WAVDEVTEAM** [comment]
Change new Exception to new \ErrorException

**Comment by KyranRana** [comment]
v3.0.0 out now.
