### ISSUE TITLE
Fatal error: Uncaught Error: Unsupported operand types in \src\CloudflareBypass\CFBypass.php(231) 

### ISSUE THREAD

**Issue by lilianorien** [KyranRana/cloudflare-bypass#107]
I have error:

Fatal error: Uncaught Error: Unsupported operand types in \src\CloudflareBypass\CFBypass.php(231) : eval()'d code:1 Stack trace: #0 \src\CloudflareBypass\CFBypass.php(231): eval() #1 \src\CloudflareBypass\CFBypass.php(127): CloudflareBypass\CFBypass::getJschlAnswer('<!DOCTYPE HTML>...') #2 \src\CloudflareBypass\CFBypasser.php(137): CloudflareBypass\CFBypass::bypass('<!DOCTYPE HTML>...', 'https://predb.m...', true) #3 \src\CloudflareBypass\RequestMethod\CFCurl.php(33): CloudflareBypass\CFBypasser::exec(Object(CloudflareBypass\RequestMethod\Curl), 'CFCurl', Array) #4 \examples\curl.php(18): CloudflareBypass\RequestMethod\CFCurl->exec(Resource id #6) #5 {main} thrown in \src\CloudflareBypass\CFBypass.php(231) : eval()'d code on line 1

**Comment by KyranRana** [comment]
Fixed in the new version v3.0.0
