### ISSUE TITLE
Why do I have to complete a CAPTCHA?

### ISSUE THREAD

**Issue by DrPaw** [KyranRana/cloudflare-bypass#119]
<title>Attention Required! | Cloudflare</title>
<meta name="captcha-bypass" id="captcha-bypass" />
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>

<script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="challenge_headline">One more step</h1>
        <h2 class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to access</span> www.betlima113.com</h2>
      </div>
      
      <div class="cf-section cf-highlight cf-captcha-container">
        <div class="cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">
            
              <div class="cf-highlight-inverse cf-form-stacked">
                <form class="challenge-form" id="challenge-form" action="/cdn-cgi/l/chk_captcha" method="get">
  <input type="hidden" name="s" value="4c76de22e59cdd799cc33fcc04d2930d7a81013c-1563216977-1800-Ae8dyRz/wzlX5x63Y8+eJMRcEdRGLL47nqZ/SlCX5QaVU1mup3UGYgYpVm7dFGuJcMO6RvE1yKazGNKOk1ekXnJZhKEmKMfRH2QzVv+XVdxAmm7u93bWKZoD1IYeXyeu4H3DGSkVQ13ML9TjuX4S+Pzj9rYa48OTqWuuKXMnnsIvsMcMvILNmnQmvoPLQZXDjQ=="></input>
  <script type="text/javascript" src="/cdn-cgi/scripts/cf.challenge.js" data-type="normal"  data-ray="4f6df49b38a4b4d2" async data-sitekey="6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0"></script>
  <div class="g-recaptcha"></div>
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
    <div><div style="width: 302px">
      <div>
        <iframe src="https://www.google.com/recaptcha/api/fallback?k=6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0" frameborder="0" scrolling="no" style="width: 302px; height:422px; border-style: none;"></iframe>
      </div>
      <div style="width: 300px; border-style: none; bottom: 12px; left: 25px; margin: 0px; padding: 0px; right: 25px; background: #f9f9f9; border: 1px solid #c1c1c1; border-radius: 3px;">
        <textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid #c1c1c1; margin: 10px 25px; padding: 0px; resize: none;"></textarea>
        <input type="submit" value="Submit"></input>
      </div>
    </div></div>
  </noscript>
</form>

**Comment by DrPaw** [comment]
Hey KyranRana Are you there. Help me pls :(

**Comment by WAVDEVTEAM** [comment]
use http for requests

**Comment by DrPaw** [comment]
I tried them all, but it didn't pass.

**Comment by WAVDEVTEAM** [comment]
use my code for bypassing, you require min php 7.2

**Comment by ash121121** [comment]
Im getting the same issue. im using php 7.3

**Comment by KyranRana** [comment]
Try the new version v3.0.0
