### ISSUE TITLE
location header issue

### ISSUE THREAD

**Issue by Sarfroz** [KyranRana/cloudflare-bypass#12]
hi sir, generally if there is url abc.com and we use its cookie then using curl it give me
Location: http://xxxxx.com

but with your code i am adding both site cookies and cloudfare cookie with method post , page is showing the data but i am not getting Location header in response.

**Comment by KyranRana** [comment]
Try version 2. There are some useful examples in v2/examples

**Comment by Sarfroz** [comment]
hi sir how can i pass my own cookies with request of url and also is there any way to use these headers 
curl_setopt($ch, CURLOPT_HEADER, 1);
curl_setopt($ch, CURLOPT_NOBODY, 1);
