### ISSUE TITLE
KyranRana Help Pls

### ISSUE THREAD

**Issue by DrPaw** [KyranRana/cloudflare-bypass#129]
Error.log

`Stack trace:
#0 /home/betrost/public_html/src/CloudflareBypass/CFCurlImpl.php(83): CloudflareBypass\CaptchaPageImpl->getClearanceUrl('--> ')
#1 /home/betrost/public_html/index.php(29): CloudflareBypass\CFCurlImpl->exec(Resource id #3, Object(CloudflareBypass\Model\UAMOptions))
#2 {main}
  thrown in /home/betrost/public_html/src/CloudflareBypass/CaptchaPageImpl.php on line 16`

Website that will draw data  www.danobet1.com

**Comment by KyranRana** [comment]
Use the ticket which you have open already. Don't create new ones.
