### ISSUE TITLE
Having errors on "cookies.txt"

### ISSUE THREAD

**Issue by justinsalvacion** [KyranRana/cloudflare-bypass#13]
Whenever I try to run the code, i am having **unlink(cf-cookies/cookies.txt): No such file or directory in public/XXX/XXX on line 65**

**Comment by freeman3s** [comment]
I have the same problem

**Comment by kavin-90** [comment]
i've same problem.

thanks freeman for help

**Comment by KyranRana** [comment]
Fixed in the latest commit. 👍
