### ISSUE TITLE
Which minimum php version this script support and can it use crontab to run ?

### ISSUE THREAD

**Issue by yumedia** [KyranRana/cloudflare-bypass#132]
I have two questions:
1. Which "minimum" php version to run this script?
2. After setup this script to my PHP file, can I use crontab to auto run this PHP file to curl with the time I want on Linux server ( Centos 6/7 version ) ?

Thank you for great script and support!

**Comment by KyranRana** [comment]
PHP 7

You should be able to. There are some further updates coming up to attempt to fix the header order. The new version of cloudflare is a bit anal about the order which headers are sent during validation. So I need to do some more refactoring to ensure that is accounted for.

**Comment by momala454** [comment]
i just got this warning, just once.  

PHP Warning:  usleep(): Number of microseconds must be greater than or equal to 0 in /CloudflareBypass/vendor/kyranrana/cloudflare-bypass/src/main/CFCurlImpl.php on line 200
