### ISSUE TITLE
'CloudflareBypass\CFCurlImpl' not found

### ISSUE THREAD

**Issue by snout** [KyranRana/cloudflare-bypass#134]
I'm trying the example, after having used composer to install. Php newbie, totally.

$ php7.0 curlbypass    # [which is the main README.md example]
PHP Fatal error:  Uncaught Error: Class 'CloudflareBypass\CFCurlImpl' not found in /var/tmp/curlbypass:18
Stack trace:
#0 {main}
  thrown in /var/tmp/curlbypass on line 18

PHP 7.0+49 debian  "7.0.33-0+deb9u3"
libcurl3 7.52.1-5+deb9u9
openssl 1.1.0j-1~deb9u1

**Comment by WAVDEVTEAM** [comment]
Fatal error: Uncaught Error: Class 'CloudflareBypass\CFCurlImpl' not found , idm, I get the same error, I installed everything with composer

**Comment by ash121121** [comment]
Try setting the full path to the autoload.php file?

**Comment by WAVDEVTEAM** [comment]
what do you mean? The autoload finds it for me

**Comment by snout** [comment]
Also and uuh, since this is the first time ever I've even used composer (whatever it's really for), where _do_ I find the files such as autoload and tell the main program to use it?

(Meanwhile I found cfscrape that does what I want - connect site, wait out the CF timer in im-under-attack-mode, hands back cookie and user-agent string for reuse in cURL, wget or any other non-CF-aware program.)

**Comment by WAVDEVTEAM** [comment]
You must first create a folder on your server, then install the Kyranrana library using composer, then restart apache, then download the extension created by kyranrana from github and take all the files contained in the scr / main folder, and put them in the folder that you had previously created to install composer and then restart apache again

**Comment by ash121121** [comment]
So much effort. All I do is download the zip and upload to a folder. CD to the folder containing the .json file and run "composer install" and its done

**Comment by snout** [comment]
> You must first create a folder on your server, then install the Kyranrana library using composer, then restart apache, then download the extension created by kyranrana from github and take all the files contained in the scr / main folder, and put them in the folder that you had previously created to install composer and then restart apache again

Ohgod. >.< I don't even have apache installed, just a lighttpd for basic serving needs. This is growing way too big to be worth it for me. :p

**Comment by ash121121** [comment]
Its actually alot simpler than wavdevteam is making out.  Don't be put off contact me and I'll help you

**Comment by snout** [comment]
Thanks but nah- cfscraper already does the job for me.

**Comment by ash121121** [comment]
Yeah php isn't really the framework for this job.
