### ISSUE TITLE
I have error with captcha

### ISSUE THREAD

**Issue by WAVDEVTEAM** [KyranRana/cloudflare-bypass#135]
I get this error!
Unknown error -> --> [Captcha] ERROR. captcha page found. No implementation exists for this yet!

link is
https://seriehd.zone/

**Comment by KyranRana** [comment]
Try with version 3.3.0 ? And try with the new example code.

**Comment by KyranRana** [comment]
Closed due to inactivity.

**Comment by WAVDEVTEAM** [comment]
I have new version Kyranrana
