### ISSUE TITLE
Notice: Undefined index: request_header in \src\main\CFCurlImpl.php on line 92

### ISSUE THREAD

**Issue by yumedia** [KyranRana/cloudflare-bypass#138]
Sometimes I got this error 

Notice: Undefined index: request_header in \src\main\CFCurlImpl.php on line 92

**Comment by KyranRana** [comment]
You need to set CURLINFO_HEADER_OUT to true when requesting the webpage. That is one of the prerequisites when using cURL.

**Comment by WAVDEVTEAM** [comment]
Kyranrana you can help me?

**Comment by yumedia** [comment]
I'm also get these error:

Notice: Undefined offset: 1 in C:\xampp\htdocs\cloudflare-bypass-master\src\main\Model\UAM\UAMPageFormParams.php on line 35

Notice: Undefined offset: 1 in C:\xampp\htdocs\cloudflare-bypass-master\src\main\Model\UAM\UAMPageChallengeCode.php on line 53

**Comment by KyranRana** [comment]
Try with version 3.3.0 ?

**Comment by KyranRana** [comment]
Closed due to inactivity.

**Comment by nimah79** [comment]
Still have this issue:
Undefined index: request_header in src/main/CFCurlImpl.php on line 117

**Comment by yumedia** [comment]
If use curl_setopt($ch, CURLOPT_COOKIEJAR, "cookies.txt"); and curl_setopt($ch, CURLOPT_COOKIEFILE, "cookies.txt"); still get 

Notice: Undefined offset: 1 in \src\main\Model\UAM\UAMPageFormParams.php on line 35

Notice: Undefined offset: 1 in \src\main\Model\UAM\UAMPageChallengeCode.php on line 53

**Comment by KyranRana** [comment]
Can you give me the full code you are using to perform the request?
