### ISSUE TITLE
Any example? I got the cloudflare redirect page content

### ISSUE THREAD

**Issue by yylzcom** [KyranRana/cloudflare-bypass#151]
When I run the code on the README page, I got the CloudFlare redirect page content, any help would be highly appreciated.

**Comment by drps** [comment]
it seems you are using 3.3.0 version of the package, if so you should use updated version from last commit or wait for a new release

**Comment by yylzcom** [comment]
@drps  Thank you! I will clone from github and try again.

**Comment by zikju** [comment]
Same problem to me. 
I'm using latest version of this package and getting cloudflare redirect page.
Any help?

**Comment by drps** [comment]
can you show logs and/or cloudflare page content which causes this error?

**Comment by zikju** [comment]
@drps I rolled back package version to this commit:
https://github.com/KyranRana/cloudflare-bypass/tree/4e7a6f57df9884e450e7e02ef067425cc1f8801d
And now its working fine. I believe problem was with "r" input.
