### ISSUE TITLE
I have error getDataType() on null in master (2019-11-28)

### ISSUE THREAD

**Issue by jokecup** [KyranRana/cloudflare-bypass#152]
![20191130_042245](https://user-images.githubusercontent.com/9822139/69890638-6c502500-1329-11ea-9244-fedf7ee39996.jpg)

**Comment by drps** [comment]
[CFCurlTest.php](https://github.com/KyranRana/cloudflare-bypass/blob/master/src/main/Example/CFCurlTest.php) is works for me for https://predb.me/?search=720p

can you show cloudflare page content which causes this error?

**Comment by jokecup** [comment]
https://jsfiddle.net/wpcam782/

**Comment by drps** [comment]
i dont know why but for some reason your script puts empty string to `UAMPageAttributes` constructor as a page content [here](https://github.com/KyranRana/cloudflare-bypass/blob/master/src/main/CFCurlImpl.php#L146)

does [curl_exec](https://github.com/KyranRana/cloudflare-bypass/blob/master/src/main/CFCurlImpl.php#L139) works as expected?

**Comment by jokecup** [comment]
I try change [here](https://github.com/KyranRana/cloudflare-bypass/blob/master/src/main/CFCurlImpl.php#L128) to 
curl_setopt($curlHandle, CURLOPT_SSLVERSION, 4); 
it works for me
