### ISSUE TITLE
the script runs endlessly 

### ISSUE THREAD

**Issue by dimkar121** [KyranRana/cloudflare-bypass#153]
Hello, the script runs endlessly providing no results.
I attach a screenshot

[INFO] UAM (retry: 0) -> applying HTTPS settings
[INFO] UAM (retry: 0) -> waiting for 5 seconds!
[INFO] UAM (retry: 0) -> getting form params...
[INFO] UAM (retry: 0) -> (r param: 0760bd7430b6044a4dd3534fd8a08aa56e46884d-1575106500-0-Ae419L7TDsQXjCBWru3aUYkKmT3E2cjvo23NO0Sc15dvn1uluIn7MZF1jD9iu3i1ag6I2JS1q+7ACm5dWtBnwfxG20kmszAMGA3iWzNrs9r0Ra4rFLxZLi4aCIr3vhFQ7I9TcrRwUyJWV4zdWOH7WLdoZPY0PbTNV7WFnj1a8HHcArbO1wQyHkn70hn1qGKPHB8K6183ei3oKdRbMAgDje3GUcx5RpS1GNxqeNjdBVe/kSX3FOVI2Fbk+B74lTMwzmbzrtTYTJkmnGtprwJC2G4o40IGjG8iapGqnIOA6kRK0Nx7heAaoAziZE8UGmdT2esqhBAukV7QAxf8r2TkFlBNWBPHdG2KLJlliM0s9DtsNHBky+PVcbMZoHez/wgq5JLqS5a0trttwmqGfII/ZFWjq4BhQQ/MJaWkwEFOkNdky0QrIOVAyz3WVPRG2j56KZ7QMOYtcaWj/5GcVqEoAexi/ZfZsV2gY5Ie4l5pigervQsJ89FKiU3xhSxEQN6XvFZ1l0Y2A1ugkKm7Fj8mbCVvBdVg3zn+2e0RKVzoHtfjmrFjs3fl6onMG4Qi/Uj8H4Q1M9XbW0AmlkDO1KVZ+KShQ5ftkc5lJo4wQetrmHMFis5xHQ2DoKptcxiItRhQJ/0bbZrD2QTf3nV0deqdWvJ+0EA6MAK9667vQ395cg5p0W/qaTbEysbNt+LX9jwUwKmMvxgMT6akqxYTj6I89xiqpj5RDIiJ3aHgczWSPaYrYOesAJB2fjzlXnk2B7DsWESXrk3+dQBA+8k6oAh88Qpt2zJGJiqA8WfrA3TWMKRyupL68U41uv047J9T8O3K2Fs6TzBV8WSAUxUAe9U3YGgepgj6Kyw6mt8pfHAeRIz4FNZvRCdFQ7eTtsWu2iQ/M7VtrAPMzOlx0Kw1j3VwY9pyI+QWi/DP9aIgOH7OJHJJDBhufY7f5hsYFM1PmuQyyXBr+69z7TIxBJ07mpLBI3X3LCCFv+6n4A5zRFhoSqypn7eVhbL4fnSFJGANEBp7Qde1ObhvQPYAXFWL6MtSrSnWJs2tR9IsjjZiym7RJ2yFaDU6ck0W0onh4tarRyxrBY0SYHvebWmyQpJ/gIFsCGihOAnt2+67GHo5N+0Pbqfkh4y32WSsAvvS9oYm4TAO7bhV4YKn+aq0E5S9bi+LmpjbCj2sahQuqNrsvgXubczZZWJv2kFGfgsNQX7js/C8geOEZYT+m2OP61hZaLxwHgy5Ka3iswfYfEnkPDo5lfBMydfNn0GGnUlT14hUWyaWDRNAArKIeFKE5BeySODccOONNb/wPm9JGIrJ5nHFuHiubY17SdX4yTcHjBX3Sx72y3IAlM4N+3PhPGBnLP5pa03IsGkUC7V5Gj2xSRuUTIyeaFPBsRcMyQUC3CrYZ8ajPoYTo78qjLSbjXmBmbhMj8wxMue9OJheydzWSZaQfk2wkw3ZNkbBeDnUd9CZR5S5AfjE1g3tBRnHJiByhlKSX+B/zE30j8Lh17Emz/r5ofXj)
[INFO] UAM (retry: 0) -> (jschl_vc param: edad0b121960f61c713966c1159beee7)
[INFO] UAM (retry: 0) -> (pass param: 1575106504.712-EbTctt90Wx)
[INFO] UAM (retry: 0) -> (jschl_answer param: 8.670749893)
[INFO] UAM (retry: 1) -> applying HTTPS settings
[INFO] UAM (retry: 1) -> waiting for 5 seconds!
[INFO] UAM (retry: 1) -> getting form params...
[INFO] UAM (retry: 1) -> (r param: f801c026db6b1369e8a81cb40eceb44017ad8f2c-1575106505-0-AYfjJ43pP46yOo3GEB1NsCCswDHxZ+Lw75Au42I15Tnt9+QnIG1DUbR1YgIllWOLlzuR2X605fcQI5A6MajFCUcY/mXSUfqkjbMnyQA8WNSVA1tU+8MYjBcmwll0IHkdBopxl4yJvhmXgr8pHG+AKSf4xuN6G5u6i8vxh2A3gW3MJ/yorvbAu55xAyKTlG1CnjLHNtLMYNY8c5svcmaHYHl9qVnpRKNAyr0nl03q/mqT7e77l3OX7yxZqUkaCg50+RLIVqrqMl6wLdczh/2/Ppysi635qlKJaqJ/vqCM9kaaMMtcjGa1htlZGaUeuii3aozxXOWQIIVBSujTsCcpsSiYcjkCCC2cfpO0B3d4JyuTi3Wy/rCtJkoSNOnNvJ/tkvYkT9IpH4LW5aQEBCNdFhJWEdOuj2IaeOrnaVKDQBQ+YpnYuuKHv1vG2xTdQtCFG9V4jcpwfeKS7EWoXxpfwWZFn6+sa6+3tYeVoi0ohXTRarhB6iCzacH3TnBb35XMfjxszTq6AQHEtbP+q9J5kGiRwdM9F9q6CPv4e9hzRaYDJBx1f1uyHWo2Eh7mlgXDPou5hoUMoDqR/t9d+bnMuf6BBC75ygwjvx4Qr8xQR6Zzg3JgrI+g+mHaz4LujTIsb+1KKdo4VRZVhjOLOK13yex3lFgFHOQ3LzriqvJMTbFAR/vWOlT8+GNyJ2SuVnJe5I/IXcOyTdIxDach+gqOkgRVhG2g/J3MYpUc0OGiPwLZWhZIFMPL2mliAXjYzn130AlyvlnGS3iaCnX8Pq2xt4PeWsuZAE68j55usx95AyspF70m8uH2qoimhrYfEKXApiJbYzV2ln4V75I0DHqXkP+UsxL+DXqGhztndBZSEUa+R+esCeQSFQ9iLXMimC+E+cJ8Yo+MkBlNHVCtXZP8EX3X6UL0O1MTbAR/0394D40UN0h8lRtSrDGqamfbylQFGKpu+QYOHPEB2B3z22aSkC/b1q6JHpPSm3sTyJIC7pXJYhNOTEEX98rPRNIp/AnIT04R669OJtjBZ+J724j/nKsoJPBkAB7bhVpq4JuFPfFsuSoO46OwAkOxs2wAzlZRj+FJbiVua5SGfeIIJ5xzrL7QdMePvx8JfAjF8jmwQUX+QUXUwucSjAUcIULUqf4ygFl1XyA3SnrDEaC4yaT+JwwZeWRrl5jlbx9ulEjzM7RQoTyKixVtkeSCkDWVe+dIvZfRYqW0QJN2iKD8UU9DTMjWklLJEtXH2aDAO7eu7YXc+KTh/atgXwCF+pCvutjIUUENtEgkDB5GD6FAIbcSF44AES3y1SMw1gEIerTDthROpoVUuIiYl1U/NCawVyKQiwlTMIIQQfAY25+QES5On1HVj38t6bDOL3FuxWNO311c)
[INFO] UAM (retry: 1) -> (jschl_vc param: 397075c937939813ae0b3e17c21e505b)
[INFO] UAM (retry: 1) -> (pass param: 1575106509.817-KzraqiH8TE)
[INFO] UAM (retry: 1) -> (jschl_answer param: 4.786560004)
[INFO] UAM (retry: 2) -> applying HTTPS settings
[INFO] UAM (retry: 2) -> waiting for 5 seconds!

**Comment by drps** [comment]
can you show cloudflare page content which causes this error?

**Comment by dimkar121** [comment]
It's a classic cloudflare page that counts for 5 seconds, nothing particular

**Comment by dimkar121** [comment]
I can send the url in private

**Comment by drps** [comment]
you can check whether [$this->uamPage->getClearanceUrl($pageAttributes)](https://github.com/KyranRana/cloudflare-bypass/blob/master/src/main/CFCurlImpl.php#L154) corresponds to form's action from cloudflare page

you can pm me via email from my profile's page
