### ISSUE TITLE
Not working for any website

### ISSUE THREAD

**Issue by WAVDEVTEAM** [KyranRana/cloudflare-bypass#155]
Not working for https://seriehd.moda or https://piratestreaming.surf/, i have latest version of code

**Comment by drps** [comment]
the first one is protected with captcha for me.
but test is successfull for the second one, you can view my output here https://pastebin.com/XJ93iNMe

**Comment by WAVDEVTEAM** [comment]
yes, but don't return the HTML page to me

**Comment by laxity7** [comment]
download the archive and update a whole code, it should work

**Comment by vvpgrp** [comment]
@WAVDEVTEAM
Try this commit: 
[https://github.com/KyranRana/cloudflare-bypass/tree/4e7a6f57df9884e450e7e02ef067425cc1f8801d](https://github.com/KyranRana/cloudflare-bypass/tree/4e7a6f57df9884e450e7e02ef067425cc1f8801d)
