### ISSUE TITLE
[ERROR] UAM (retry: 0) -> clearance cookie missing! Unknown error -> CF clearance could not be found!

### ISSUE THREAD

**Issue by gergokee** [KyranRana/cloudflare-bypass#158]
For example for predb.me, for other sites, it is just running forever. So current version (i have latest updated files) is not working.

**Comment by nitemare** [comment]
Getting a '[ERROR] UAM (retry: 0) -> clearance cookie missing! Unknown error -> CF clearance could not be found!' Error, an its just returning the cloudflare page. 

does anyone know what causes this? why is the cookie missing?

`URL:https://torrentz2.is/
[INFO] UAM (retry: 0) -> applying HTTPS settings [INFO] UAM (retry: 0) -> waiting for 5 seconds! [INFO] UAM (retry: 0) -> getting form params... [INFO] UAM (retry: 0) -> (r param: 3168e8c9698629f2bdbb949cd1d434dbe12884a6-1584142586-0-ASFSSlDO1zVC6hCCtMgcmSp2uvSN3PWnlP/aujJoiloFXVHydxZc0tG/rnbyXmsBob6Z++zWoIXAeg8hdiY39sza4liDfuuYqu+gJlqfxY/vvljFVrhxdEZrFCuSEwcV2I5DPt/fIoW501+rZ6+baCYAfdKsMfn4c8qYEpvZLoe8AjvN7Ika/6pNdVevE7NJecK44SPz79uEmup7D8JThHD91JOxVvWJxDG2ZylZIK/P72N5Q5DtQAB8gQOscETXNQ5hfdVHgg5PqgMUVuBMCvKRTxAAC7f5VsthOd4p77LGI68e5h1sRfDR/D7dEXdcHCy+frvZ2O3OOlBfA/6MbvJc01RNTYR8mo4E1hbtAc0hp7AmV2ha1eizwtoYU3T6gFFl6c1AclYLDWVVtmE77Xc1bCXb/+r09k6ICAsFGIBDR4sAYAqSW5ewt9vbIa6trYFLj9jA6P92PYdeURgwPopqQYT0Vnjo+Ckm/RKRLPsnbTOr297OsRi82V8DRf199Yj2w86bSZvjwDp0jqI0KxuJ9NTKOfEAYI/eKXIpJ6EBWjbH5qNUp8m9W+vYqTRtUYhz+PBFkvijK2yxUGc/OwVaTYE6Tg5glB3X66bYNTSGWNNOaDr9jobpHTfTq+gS2nCS48TYyYT/+ZEu3UDdWElSyimv2Z6ehU9UYa+i3sBm4AKE8KQ4cBMRzLZTIXBSwEJpZqFIQzhLOHFBjKRMdZWF0q5ukNWwaVeYF+20YApRZl5jcVByD1EG8Jy1izYoK/vvK4JQ5YyIj9OvuInLmyrZya/osUlPfCdz5ZWh1SItN3yg4jyp3myVPllYV4UPRAJ+mKHI4gZ41MQLgip+vbaJ4Gc2wqXsvwYNTTRudx2FZHV139IabUUtihm4BYRkE2ivbzu+e922T4NKQnTIPA2ETjWFQJiEG9y+YD4l79679Dc7ET9Mr3MNODnc85knTDd+Si6iKRkBouzvXbrzvVwe1wFUHIGzyOJ80KYwwExQ+h+rYdby2YuE2CBEv2v1CXPf+awBAfJJbWkQ6o6pXLv8ykR2+ea5nCPXyEopfmHSK8lFgOgezuJAHV58KMTNCmC+NTEQ93GOLwXXHGtuDTUDQJKIc0FU501XRvMXGWgEewNGTow9fiXTlQELsqnJB8K7oebRciYqS4jCg8rcmjrRZHWspPieuJGyascJLqIiVn4s5C4axNEA1MEJuawfp1a+9l53zj8oJk1is5njr6/wCqs8YyXF5SCUCpnKTyXLcEhnf6lUyxIuyr6aFPCFrG5vxzKO5AXaaSQGNMpOAKk9YK0eoImrbE/HcF6fRM3mtqrO+8DZ97Zhq29ite+LraOW4MfjCPtmPAM0Wdd5UozXRZlarO3TrNxbx3AdYBl2uYtGm6bxY8pgfW09BoiXSd3oefL1KMR02L9h7Abtr5qE5GjzR/yqNZb7VJDHIPDoJ7SheVEr49Bj2kqK9USp6hupf+HImSBvox8MBa5WsSZXxlrk9Zn+mWZyUUYkEcArtox1wPH6M5wVJ+0dn1wnRoq593rDCOjfvvcoqMgYO8KMAzdYgO+Nby4JfK449nNMO5se1yQ3rrTx9/O+J1g/zg==) [INFO] UAM (retry: 0) -> (jschl_vc param: 304a3a1a3389036230963442ddde46b9) [INFO] UAM (retry: 0) -> (pass param: 1584142590.183-JeqincQbPE) [INFO] UAM (retry: 0) -> (jschl_answer param: 6621.5700773324) [INFO] Array ( [0] => #HttpOnly_.torrentz2.is TRUE / FALSE 1584411391 __cfduid d68a05bf286bfe6731bee183b4bfe65351581819391 ) [ERROR] UAM (retry: 0) -> clearance cookie missing! Unknown error -> CF clearance could not be found!`

**Comment by nitemare** [comment]
does anybody know how to correct this error? other people are saying the sites (like 'https://torrentz2.is/') work, but this error is the best i can get.

`[ERROR] UAM (retry: 0) -> clearance cookie missing! Unknown error -> CF clearance could not be found!`

**Comment by momala454** [comment]
i don't see how the commit make any fix to the different closed issues  ...
