### ISSUE TITLE
Return CloudFlare HTML

### ISSUE THREAD

**Issue by cristophermr** [KyranRana/cloudflare-bypass#160]
Hi, 

The script return the cloudflare HTML, don´t work, please help me thanks !

**Comment by AlexandrKane** [comment]
Hello, i have the same problem, please help

**Comment by nitemare** [comment]
I'm getting the same issue, trying to access the site: http://torrentz2.is
It just returns the cloudflare page
just update to PHP v7.3.14 (was having the issue on 7.1 too)
