### ISSUE TITLE
Could not fetch CloudFlare clearance cookie (most likely due to excessive requests)

### ISSUE THREAD

**Issue by adamdupuis** [KyranRana/cloudflare-bypass#19]
I'm getting this error on run.php when I use it for a URL that always goes through the CloudFlare "Checking your browser" process. Am I doing something wrong? I haven't changed anything in the script and `cf-cookies/cookies.txt` appears to be functioning correctly.

**Comment by KyranRana** [comment]
Which link are you trying to fetch?

**Comment by adamdupuis** [comment]
https://crypto-loot.com/signup

**Comment by KyranRana** [comment]
I'll take a look. Be aware I am rewriting this class at the moment. 

I'll keep you updated.

**Comment by KyranRana** [comment]
Fixed in the latest commit. Let me know if it works 👍

**Comment by adamdupuis** [comment]
Thanks for the quick update! I'm not noticing a difference on my end though :/

**Comment by KyranRana** [comment]
Have you tried pulling changes from master? I have tested it with recent master build and it works :)

**Comment by adamdupuis** [comment]
I tried quickly replacing cloudflareClass.php with the new changes. I will try replacing all three files later. I did notice there wasn't a cookie.txt file anymore and when I created it in cf-cookies/ it was deleted after running the script again.

**Comment by KyranRana** [comment]
Let me know how that goes. 👍

**Comment by adamdupuis** [comment]
Looks like it's working! I'm not seeing the Cloudflare "Checking your browser" page anymore though - is that normal?

**Comment by KyranRana** [comment]
Unfortunately no. Cloudflare uses Google Recaptcha service which is impossible to bypass.

Getting past the captcha service will require going one level further and resolving the actual IP of the site.
