### ISSUE TITLE
math eval no longer works.

### ISSUE THREAD

**Issue by taorus** [KyranRana/cloudflare-bypass#2]
Since the last may,14 the calc no longer matches, they changed the code.

**Comment by kavin-90** [comment]
working correctly no problem yet. I tried yesterday it works.

**Comment by duayres** [comment]
`'jschl_answer'  => ($answer-12)`

...and it worked o.O

**Comment by duayres** [comment]
Ok, theres something related to the siteLink variable, when I change it the diff of 12 goes up or down, so i'm figuring out, maybe something i've touched and gone bad on your source, but i'm pretty sure i'm not touched the url's variables. There's any minimum version? I'm using php 5.3 and the bypass doest return the Set-Cookie header with the cf_clearance:

```
HTTP/1.1 302 Moved Temporarily
Date: Wed, 01 Jun 2016 19:03:15 GMT
Content-Type: text/html
Content-Length: 165
Connection: keep-alive
Location: http://www.eduardoayres.com
Server: cloudflare-nginx
CF-RAY: 2ac4ecb2cee70fb8-GRU
X-Frame-Options: SAMEORIGIN
```

The sent headers are:
```
GET /cdn-cgi/l/chk_jschl?jschl_vc=a007a586c771260f9e533364d55a2894&pass=1464769808.574-99nXAdDwrn&jschl_answer=-1166 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36
Host: www.comerciourbano.com.br
Accept: */*
Referer: http://www.eduardoayres.com
Cookie: __cfduid=d10585010072b86ed46c5afddd798aa381464766980
Connection: Keep-Alive
Upgrade-Insecure-Requests: 1
Accept-Language: pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4
```

Maybe something is missing on the answer headers? maybe its my cURL version?
PS: Captured RAW headers using wireshark, just to be sure.

**Comment by KyranRana** [comment]
Can I ask the site which you are trying to connect to? I seem to be testing it and it works fine so I am kind of confused where this problem is arising. :)

**Comment by taorus** [comment]
Problem solved, updated my entire php and extensions and it worked :).
You can delete this issue (if it's possible xD)

**Comment by KyranRana** [comment]
No worries, glad you managed to find out what the problem was 👍

**Comment by kavin-90** [comment]
I'm getting now 

**```
Fatal error: syntax error, unexpected end of file

cloudflareClass.php(261) : eval()'d code:10]
```**

**Comment by KyranRana** [comment]
Let me look into this

**Comment by KyranRana** [comment]
That should now be fixed, please be sure to open a new issue thread if you run into an issue :) 

I don't normally go checking closed threads haha

**Comment by kavin-90** [comment]
okay. Thanks
