### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tinloaf** [KyranRana/cloudflare-bypass#21]
Hi!

Would it be possible to add a license to the project, so that others can use your code? If you intentionally did not add a license, that's of course fine, too, but would mean that nobody can (legally) use your work. :(

Thanks a lot!

**Comment by KyranRana** [comment]
CloudFlareBypass version 2 is coming in a few days and it will have a license 👍 

Is "Unlicensed" a good choice to go for?

**Comment by tinloaf** [comment]
Not if you want people to be legally able to use your code, I think. But I'm not an expert on this one. Have a look at https://choosealicense.com/ - there's a "I don't want to" option on the bottom right.

**Comment by railken** [comment]
@KyranRana Please add one

**Comment by leonhuangplus** [comment]
@KyranRana 
Hi KyranRana
We would like to ask your permission to license CloudFlareBypass, would you please contact us via leonhuang@asustor.com.
Waiting for your reply. Thank you.

**Comment by railken** [comment]
@KyranRana This issue can now be closed.

**Comment by tinloaf** [comment]
:tada: Thanks!
