### ISSUE TITLE
401 http_code

### ISSUE THREAD

**Issue by freeman3s** [KyranRana/cloudflare-bypass#22]
I am trying to get information from site but I've got "http_code": 401

**Comment by KyranRana** [comment]
Which site are you trying to fetch?

**Comment by freeman3s** [comment]
@KyranRana this https://csgoempire.com

**Comment by KyranRana** [comment]
This will be fixed in Cloudflare Bypass v2. I will be updating the main repo sometime today with the fix.

**Comment by freeman3s** [comment]
@KyranRana Thank you very much!

**Comment by KyranRana** [comment]
Try the v2 code and let me know if it works with that link.

**Comment by ZhaoSin** [comment]
I do not like v2 when have to install composer, it's not convenient like v1, just put php file -> then run.

**Comment by KyranRana** [comment]
@ZhaoSin I will add an autoload.php into the src/ folder so you just include that instead. 👍 

Also, in future, please open a separate issue.

**Comment by KyranRana** [comment]
@ZhaoSin change made.

**Comment by freeman3s** [comment]
@KyranRana https://csgoempire.com works well, but then I tried this link https://csgoempire.com/api/get_bot_items and again got 401
Warning: file_get_contents(https://csgoempire.com/api/get_bot_items): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized

**Comment by KyranRana** [comment]
@freeman3s - that link in my browser also outputs 401 after CF has validated ? Maybe requires HTTP authorisation ?

**Comment by freeman3s** [comment]
@KyranRana I opened https://csgoempire.com/api/get_bot_items in incognito and got the necessary data without authorization. It looks like it does not require HTTP authorization

**Comment by KyranRana** [comment]
Interesting. Seems like the first time you request it it works (with CF process), but after its a 401. 
All I can recommend for now is turning cache off and see if that works. Set "cache" to false.

**Comment by freeman3s** [comment]
@KyranRana how?
`<?php
require __DIR__ . '/../vendor/autoload.php';

use CloudflareBypass\RequestMethod\CFStreamContext;

$stream_cf_wrapper = new CFStreamContext(array(
    'cache'         => true,  // Caches clearance tokens into Cache/ folder under md5(site host)
    'max_attempts'  => 5      // Max attempts to try and get CF clearance
));

// Get Example: 1
$opts = array(
    'http' => array(
        'method'=>"GET",
        'header'=>
            "User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36\r\n"
    )
);

$url = "https://csgoempire.com/api/get_bot_items";
echo file_get_contents($url, false, $stream_cf_wrapper->create($url, $opts)); // As easy as that!`
Here is my code and I've got 
Warning: file_get_contents(https://csgoempire.com/api/get_bot_items): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized

**Comment by KyranRana** [comment]
I'll take a further look. I will update the issue when I have some more information on this.

**Comment by freeman3s** [comment]
@KyranRana I understand correctly?
You just changed $url in streamcontext.php file and it works?

**Comment by KyranRana** [comment]
@freeman3s I just tried loading the URL in my browser, haven't done anything code related yet. I opened Icognito like you did and refreshed the page a few times. The first time I did it, the 2nd reload triggered 401. The second time, no matter how many times I reloaded the page it loaded correctly. 

I will find out what's going on a little later.

**Comment by freeman3s** [comment]
@KyranRana Thank you!

**Comment by freeman3s** [comment]
@KyranRana I added a Referer header and everything worked. You can close this issue.
Once again many thanks for the excellent library!!!

**Comment by KyranRana** [comment]
@freeman3s No worries glad you managed to fix the issue. 👍
