### ISSUE TITLE
POST Request

### ISSUE THREAD

**Issue by joserenatog** [KyranRana/cloudflare-bypass#24]
Hello! Firstly, thanks for the development of this amazing tool !, I would like to know if **it is possible to use the POST Protocol in the CURL request**, the page where the bypass was made normally appears, but it does not detect the post inserted in the page. I await your return, preferably as soon as possible!

**PS. I'm using version 2**

**Comment by KyranRana** [comment]
No problem! Which site and what fields are you posting? 

I've tried making the process transparent as possible so it should be possible to use your cURL handle. So posting with cURL should work.

**Comment by joserenatog** [comment]
Thank you for your response. Currently, I only have one postdata, the field ** account **, I would like to know how to make POST work correctly on the curl target

**Comment by joserenatog** [comment]
**would you have an email to contact** ?

**Comment by KyranRana** [comment]
Use cURL to make the request, but use CFCurl to exec the request instead of curl_exec 👍

**Comment by joserenatog** [comment]
Do I insert my Curl code into CFCurl?

**Comment by KyranRana** [comment]
There is an example file which shows how you can use CFCurl in v2/examples.

If you want to avoid installing composer, you can replace "vendor" with "src" in the require.

**Comment by joserenatog** [comment]
I inserted the link where my post would occur, I enabled the post and inserted the postfields correctly, but the page results as if the post had not occurred...

**Comment by KyranRana** [comment]
Email me your code @ kyranportfolio@gmail.com

**Comment by joserenatog** [comment]
Ok!

**Comment by joserenatog** [comment]
Email sent!
