### ISSUE TITLE
Examples for ver 2?

### ISSUE THREAD

**Issue by ZhaoSin** [KyranRana/cloudflare-bypass#27]
Link: https://github.com/KyranRana/cloudflare-bypass/tree/master/v2/examples

What different between curl.php and streamcontext.php mate ?

**Comment by KyranRana** [comment]
Well, they both do the same thing which is bypass Cloudflare. The difference is CFCurl provides a wrapper for curl_exec, and CFStreamContext provides a wrapper for stream_context_create. So if you have a context already setup for connecting to a website, use CFStreamContext, otherwise use CFCurl.

**Comment by KyranRana** [comment]
I will document everything soon and add some more examples. But those examples should be a good starting point and how the class can be used.
