### ISSUE TITLE
where is the file vendor/autoload.php

### ISSUE THREAD

**Issue by xaiborweb** [KyranRana/cloudflare-bypass#29]
hello thank you very much for your work zip download your project and intenete execute
https://github.com/KyranRana/cloudflare-bypass/blob/master/v2/examples/curl.php

but I throw myself the following message
`Warning: require(C:\xampp\htdocs\bot\cloudflare-bypass-master\v2\examples/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\bot\cloudflare-bypass-master\v2\examples\curl.php on line 2

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\bot\cloudflare-bypass-master\v2\examples/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\bot\cloudflare-bypass-master\v2\examples\curl.php on line 2`

so I see that the file
`require __DIR__ . '/../vendor/autoload.php';`

who makes the call is not in the download, could you please upload all the necessary files, I am a novice in this composer I would thank you eternally thank you.

**Comment by KyranRana** [comment]
You can avoid using composer by just replacing vendor with src.

So `require __DIR__ . '/../src/autoload.php';`
