### ISSUE TITLE
v2 doesn't work without cache

### ISSUE THREAD

**Issue by madri2** [KyranRana/cloudflare-bypass#30]
passing false/null to "cache" in the array parameter is useless, it's ignored 
if (isset($config['cache']) && $config['cache']) {
            $this->cache = new Storage();
        }
maybe adding
else
$this->cache = null;

if not, it will crash here
if (isset($this->cache)) {
                $info = $ch->getinfo();
                $components = parse_url($info['url']);
                // Set clearance tokens.
                **if (($cached = $this->cache->fetch($components['host'])) !== false) {**
                    foreach ($cached as $cookie => $val) {
                        $ch->setopt(CURLOPT_COOKIELIST, 'Set-Cookie: ' . $val);
                    }
                }
            }

**Comment by KyranRana** [comment]
I will check this out and get back to you. :)

**Comment by KyranRana** [comment]
Fixed in latest commit. 👍
