### ISSUE TITLE
Error Scrapping

### ISSUE THREAD

**Issue by risklife** [KyranRana/cloudflare-bypass#41]
Hello, I have this error, i load the autoload from folder src.

Uncaught exception 'ErrorException' with message 'Exceeded maximum retries trying to get CF clearance!

**Comment by KyranRana** [comment]
Which site are you trying to request?

**Comment by risklife** [comment]
http://gnula.nu/

**Comment by railken** [comment]
Can you provide the code that you used?


I tried with this one and seems to work:

```php
use CloudflareBypass\RequestMethod\CFCurl;

$curl_cf_wrapper = new CFCurl(array(
    'cache'         => true,   // Caching now enabled by default; stores clearance tokens in Cache folder
    'max_attempts'  => 5       // Max attempts to try and get CF clearance
));

$ch = curl_init("http://gnula.nu/");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);

curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36');
$response = $curl_cf_wrapper->exec($ch);

curl_getinfo($ch, CURLINFO_HTTP_CODE); // 200
```

**Comment by KyranRana** [comment]
I'm going to buff up the tests a little so they test multiple sites instead of one. Tests should run the script in no cache mode, but there should also be tests in caching mode too. I'll let you know when a pull request is there @railken

**Comment by KyranRana** [comment]
@risklife Your issue should be fixed now.

Let me know if this is the case so I can close the issue. 👍
