### ISSUE TITLE
Need little fix for dev comments 

### ISSUE THREAD

**Issue by tizis** [KyranRana/cloudflare-bypass#42]
/v1/libraries/httpProxyClass.php	
        /**
	 * @param string  **$content**         Response contents
	 */
	private function populateArrayWithRequestData(**$contents**, $status, $storeFullStatus, &$dataTarget) {

$content -> $contents

**Comment by KyranRana** [comment]
Thanks, I'll fix it but V1 is deprecated and its recommended you use V2 from now on.
