### ISSUE TITLE
Need help with composer

### ISSUE THREAD

**Issue by Rosenkreuzer** [KyranRana/cloudflare-bypass#46]
Hi, I'll try to add your project using composer, but it wont work.

I use:
composer require kyranrana/cloudflare-bypass 

I get:
 Could not find package kyranrana/cloudflare-bypass at any version for your   
  minimum-stability (stable). Check the package spelling or your minimum-stab  
  ility 

How I understant, I need to provide version, because it (your project) doesnt have stable version. 

Can help me and copy paste exact line how can I introduce it to my silex project?

**Comment by railken** [comment]
Hi, this repository is still not linked to packagist (#35), so there is no command to install it using composer.

I don't know when it will be properly configured.  
We need this! @KyranRana 

If you need it right now you can make a fork, change a few things and connect to packagist yourself as i did.

**Comment by Rosenkreuzer** [comment]
I made strange workaround, instaled it from your packagist link, but used namespace use KyranRana\CloudflareBypass\RequestMethod\CFCurl; and it worked, but it worked not as I expected. Cloudflare throw an error, that i need to set a cookie. I check Cookies folder, there were file with data, but it dont help

**Comment by Rosenkreuzer** [comment]
https://ibb.co/f1yXvS

**Comment by Rosenkreuzer** [comment]
This is error i get: https://ibb.co/bBQO27

**Comment by railken** [comment]
Can you provide the url that you used?

**Comment by Rosenkreuzer** [comment]
text me something to info [at] horozo.com, i will tell you the url
there's good protection, they don't allow curl with proxy and they use 429 errors using stream_context_create, so only way to scrap is use small amount of requests using stream_context_create + cron, but it takes a lot of time

**Comment by Rosenkreuzer** [comment]
I found a solution, that helps to scrap without any problems. 
Try to use resident proxies from https://oxylabs.io/ . If you want to get script that I use and If you need a contact direct to manager, text me an email. I'm scrapping only with one line, no need to confirm cookies, captchas. Scrapping fast without problems

**Comment by blaqmajik** [comment]
If you want to use the current repository with Composer, modify your composer.json according to this:

```
    "repositories": [
        {
            "type": "package",
            "package":
            {
                "name": "kyranrana/cloudflare-bypass",
                "version": "2.0.0",
                "source":
                {
                    "url": "https://github.com/KyranRana/cloudflare-bypass",
                    "type": "git",
                    "reference": "master"
                }
            }
        }
    ],
    "require": {
        "kyranrana/cloudflare-bypass": "*"
    },
    "autoload": {
        "psr-4": {
            "CloudflareBypass\\": "vendor/kyranrana/cloudflare-bypass/v2/src/CloudflareBypass"
        }
    }
```

Note that I made that version number (2.0.0) up, as the composer.json schema insists on it and the reference could point to a branch like the current "cloudflare-bypass-streamcontext-cache-fix" as well.

Hope you guys will make a release soon and get this added to packagist, it's a very hand library and just saved my day, thank you!

**Comment by KyranRana** [comment]
The package should be available on composer now:

https://packagist.org/packages/kyranrana/cloudflare-bypass
