### ISSUE TITLE
v2 broken ?

### ISSUE THREAD

**Issue by momala454** [KyranRana/cloudflare-bypass#48]
hello
it seems to be broken, did cloudlfare changed something ?

**Comment by momala454** [comment]
PHP Fatal error:  Uncaught ErrorException: Exceeded maximum retries trying to get CF clearance!

**Comment by crackfoo** [comment]
I see this now too...

**Comment by momala454** [comment]
yes it works thanks

**Comment by KyranRana** [comment]
Merged.
