### ISSUE TITLE
Currently not working

### ISSUE THREAD

**Issue by waylaidwanderer** [KyranRana/cloudflare-bypass#5]
As of yesterday your code stopped working. Could you look into this and see if Cloudflare changed anything?

**Comment by KyranRana** [comment]
I've tested the script again and it seems to be working. Which site are you trying this script on? :)

**Comment by waylaidwanderer** [comment]
After doing some investigation, this may be an issue with the site itself. I found that it gets stuck on the "wait 5 seconds" page and never goes onto the next page.
