### ISSUE TITLE
V2 requests taking a long time

### ISSUE THREAD

**Issue by judgdredd** [KyranRana/cloudflare-bypass#54]
each request even after caching is taking up to 10 seconds every time now. Is the caching working correctly?

**Comment by judgdredd** [comment]
Found the issue in the fetch function within the Storage class

lines: 57, 63 and 64 reference a path without the directory separator /

So they never find the file and the fetch function returns false every time

**Comment by KyranRana** [comment]
Fixed in #55 

Thanks for reporting.
