### ISSUE TITLE
Proxy ip

### ISSUE THREAD

**Issue by ash121121** [KyranRana/cloudflare-bypass#57]
Could someone help me in getting this script to work using a http proxy?

i tried setting some settings in curl but no success
private static function getPage($link, $referer, $headers = array()){
		// use cURL
	if($curlResource = curl_init($link)){
			// header settings
			$proxy1 = '173.2767676.234:58378';
			curl_setopt($curlResource, CURLOPT_PROXY, $proxy1);     // PROXY details with port
			curl_setopt($curlResource, CURLOPT_PROXYTYPE, CURLPROXY_HTTP);   // PROXY details with port

**Comment by KyranRana** [comment]
Did you fix the issue?

**Comment by ash121121** [comment]
Yes I did thank you
