### ISSUE TITLE
Proxy ip

### ISSUE THREAD

**Issue by ash121121** [KyranRana/cloudflare-bypass#58]
Could anyone help me? I've added proxy ip  to curl inside V1 classes and seems working but I'm getting thousands of cookies in cf-cookies 

Thanks in advanced

**Comment by KyranRana** [comment]
It is recommended you use V2, V1 is deprecated.

**Comment by ash121121** [comment]
I didn't switch to V2 because everything seemed just working fine . But as soon as I add proxy ip into curl it generates thousands of cookies that I thought was strange

**Comment by ash121121** [comment]
What are the pros for switching to V2 ?

Thanks

**Comment by ash121121** [comment]
Using V2 now with no issues thanks

**Comment by KyranRana** [comment]
Sorry for the delayed response. V2 is just a cleaner version of V1 which is now being maintained by myself, @railken, and some other collaborators. If you come across any issues just raise them here, and I will do my best to get back to you. If I don't, @railken may do. 

Its that time where I am busy again. There are things which are still outstanding for this project e.g. licenses, versioning, and adding to packagist which I will do in a few weeks.
