### ISSUE TITLE
Files download with curl

### ISSUE THREAD

**Issue by Diab259** [KyranRana/cloudflare-bypass#6]
How to downloads (copy to server) a files with this script using https://site.com/file.xxx ? (mp3,avi,zip,rar....)
Thks for help i'm noob

**Comment by KyranRana** [comment]
Can you give me an example of a link which you are trying to target? :)

**Comment by Diab259** [comment]
Yes  please contact me to mail for private info at dabiz62[at]gmail.com thanks for  this

**Comment by nilparra** [comment]
Do you have find the problem ? I Have same issue ...

Thanks you for your help :)

**Comment by KyranRana** [comment]
v3.0.0 out now
