### ISSUE TITLE
How to use? Are the examples supposed to work as is?

### ISSUE THREAD

**Issue by bseymour1** [KyranRana/cloudflare-bypass#61]
Using the examples, curl.php returns nothing, and streamcontext returns 503 error. 

Am I missing something? How can I retrieve page results?

Thanks so much!

**Comment by railken** [comment]
Hello, are you using v1 or v2? You have also to provide the url, otherwise we can't help you

**Comment by bseymour1** [comment]
Using v2. Tried using it as is with thebot.net or whatever the example url was. Tried other urls as well.

**Comment by railken** [comment]
PHP Version?

Add `curl_setopt($ch, CURLOPT_VERBOSE, true);` before submitting the request and paste the logs here

You can check the tests [here](https://github.com/KyranRana/cloudflare-bypass/blob/master/v2/tests/CurlTest.php) for working samples

**Comment by KyranRana** [comment]
@bseymour1 Try with the new version of CF Bypass and let me know if it works?

**Comment by KyranRana** [comment]
v3.0.0 out now.
