### ISSUE TITLE
In the v2 CURL example, what does the 'cache' parameter do?

### ISSUE THREAD

**Issue by skibulk** [KyranRana/cloudflare-bypass#66]
Does it only save the clearance token for later use, or does it also cause Cloudflare to cache the request? I'm writing an app in which I want to use CURL to preload the cache on Cloudflare (UAM is off). For some reason, Cloudflare [won't cache my CURL requests](https://stackoverflow.com/questions/52150863/couldflare-wont-cache-page-via-curl-request).

```
$curl_cf_wrapper = new CFCurl(array(
    'cache'         => true,   // Caching now enabled by default; stores clearance tokens in Cache folder
));
```

**Comment by KyranRana** [comment]
The script caches the clearance tokens into the directory specified in `cache_path` (or the system temp directory).

The file which it caches cookies in is `md5( hostname of site ).txt`

**Comment by skibulk** [comment]
Thanks for clarifying.
