### ISSUE TITLE
how can i set cf clearance cookie? thank y

### ISSUE THREAD

**Issue by curla92** [KyranRana/cloudflare-bypass#67]
i would to add cf clearance cookie with v2 example. thank y

**Comment by curla92** [comment]
i added these lines….

curl_setopt($ch, CURLOPT_COOKIEJAR, COOKIE_FILE_PATH);
curl_setopt($ch, CURLOPT_COOKIEFILE, COOKIE_FILE_PATH);

is it ok? thank y

Il giorno 29 set 2018, alle ore 12:19, Kyran Rana <notifications@github.com<mailto:notifications@github.com>> ha scritto:

cache_path

**Comment by KyranRana** [comment]
Try this:

`
$curl_cf_wrapper = new CFCurl(array(
    'cache'         => true,   // Caching now enabled by default; stores clearance tokens in Cache folder
    'max_retries'   => 5,       // Max attempts to try and get CF clearance
    'cache_path'   => COOKIE_FILE_PATH  // Where to cache session/clearance tokens.
));
`
