### ISSUE TITLE
i would to use proxy with stream method

### ISSUE THREAD

**Issue by curla92** [KyranRana/cloudflare-bypass#69]
i would to use proxy with stream method, can you help me? thanks

**Comment by curla92** [comment]
<?php
require __DIR__ . '/../src/autoload.php';
use CloudflareBypass\RequestMethod\CFStreamContext;
$stream_cf_wrapper = new CFStreamContext(array(
    'cache'         => true,  // Caching now enabled by default; stores clearance tokens in Cache folder
    'max_retries'   => 5,
    'verbose' => true
));

$link='http://thebot.net/';
$var = time();
$proxy=$_COOKIE['proxy'];
$proxyset=$_COOKIE['Proxies'];

$data = array (
        );
        
$params = '';
    foreach($data as $key=>$value)
 $params .= $key.'='.$value.'&';
         
$params = trim($params, '&');

// Get Example: 1
$opts = array(
    'http' => array(
        'method'=>"GET",
        'proxy' => 'tcp://'.$proxy, 
        'request_fulluri'=>true, 
        'header'=>
            "User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36\r\n"
    )
);

if (strpos($link, '?') !== false) {
$url = $link.'&'.$params;
}else{
$url = $link.'?'.$params;
}
echo file_get_contents($link, false, $stream_cf_wrapper->create($link, $opts)); // As easy as that!

**Comment by KyranRana** [comment]
v3.0.0 out now. Stream context support was scrapped. Will be coming as soon as cURL is tested though.
