### ISSUE TITLE
Error: undefined function json_last_error_msg()

### ISSUE THREAD

**Issue by pwiking** [KyranRana/cloudflare-bypass#7]
Hi, I get the following error when trying your script.
Fatal error: Call to undefined function json_last_error_msg() in /usr/www/libraries/httpProxyClass.php on line 360

I have error 416 from CloudFlare site (failed to open stream: HTTP request failed! HTTP/1.1 416 Requested Range Not Satisfiable)
Do you have any solution for this?

**Comment by KyranRana** [comment]
Interesting again can you tell me where you got this error, which site did you request with httpProxy?

**Comment by KyranRana** [comment]
Closing. If you do come back please re-open the issue.
