### ISSUE TITLE
"Unable to fetch jschl_vc and pass values; maybe not protected" make the rest code stop working

### ISSUE THREAD

**Issue by ZhaoSin** [KyranRana/cloudflare-bypass#73]
I get this problem "Unable to fetch jschl_vc and pass values; maybe not protected" from line "echo $curl_cf_wrapper->exec($ch)" then the rest code stop working. Do you have anyway to check this line work or not? Example:

if($curl_cf_wrapper->exec($ch) == no){
echo "not work";
break;
}else{
echo "work";
...Do other code...
}

**Comment by KyranRana** [comment]
Do you have a messenger id? Like Telegram or Skype? If so can you mail me at ranakyran123@gmail.com

I can help you resolve this problem

**Comment by xing1943** [comment]
> @xing1943 Thank you so much for support!

You're welcome. Would be helpful to let us know if it works for you.

**Comment by KyranRana** [comment]
Try again with the new version. Its recommended you enable caching to stop requesting the clearance token every time.
