### ISSUE TITLE
Not working curl of v2 

### ISSUE THREAD

**Issue by WAVDEVTEAM** [KyranRana/cloudflare-bypass#74]
i get this error on my server

Fatal error: Uncaught exception 'ErrorException' with message 'Exceeded maximum retries trying to get CF clearance!' in /Cloudflarebypass/CloudflareBypass/RequestMethod/CFCurl.php:100 Stack trace: #0 /Cloudflarebypass/CloudflareBypass/RequestMethod/CFCurl.php(103): CloudflareBypass\RequestMethod\CFCurl->exec(Object(CloudflareBypass\RequestMethod\Curl), false, 6) #1 /Cloudflarebypass/CloudflareBypass/RequestMethod/CFCurl.php(103): CloudflareBypass\RequestMethod\CFCurl->exec(Object(CloudflareBypass\RequestMethod\Curl), false, 5) #2 /Cloudflarebypass/CloudflareBypass/RequestMethod/CFCurl.php(103): CloudflareBypass\RequestMethod\CFCurl->exec(Object(CloudflareBypass\RequestMethod\Curl), false, 4) #3 /Cloudflarebypass/CloudflareBypass/RequestMethod/CFCurl.php on line 100

**Comment by KyranRana** [comment]
@WAVDEVTEAM Try again with the new version and let me know if it works for you?
