### ISSUE TITLE
How to set a command on the method

### ISSUE THREAD

**Issue by topboy12** [KyranRana/cloudflare-bypass#78]
I am trying to use this on layer 7 but i dont know which command to type and i dont need bots or proxys just my vps, anyway you will update this for UAM and can bypass also captcha?

**Comment by topboy12** [comment]
sir give me ur discord

**Comment by KyranRana** [comment]
Hi, I don't use discord. You can add me on Telegram at CoolioPD

**Comment by topboy12** [comment]
Okay wheres the last version update php for uam Clouflare bypass, tell me the command how it works

**Comment by topboy12** [comment]
> Hi, I don't use discord. You can add me on Telegram at CoolioPD

add me https://t.me/cekboy
