### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by bootiehandler** [KyranRana/cloudflare-bypass#8]
Parse error: syntax error, unexpected '<' in cloudflareClass.php(261) : eval()'d code on line 1

Notice: Undefined variable: answer in cloudflareClass.php on line 263
Could not fetch CloudFlare clearance cookie (most likely due to excessive requests)

**Comment by KyranRana** [comment]
I'll look into this, could you tell me which site you got this error for?

**Comment by KyranRana** [comment]
I'm closing this as you seem to be inactive. If you do come back, please reopen the issue.
