### ISSUE TITLE
how do i add this

### ISSUE THREAD

**Issue by bert-w** [KyranRana/cloudflare-bypass#81]
it is not added to packagist composer repo. Also there are 2 versions in here.

**Comment by j0k3r** [comment]
I suggest to @KyranRana to:
- create a branch called `1.x` from the current master
- remove the `v2` folder from that branch
- move stuff from v1 folder to the root
- tag `v1.0.0` on that created branch
- go back to the master branch
- remove folder `v1`
- move stuff from v2 folder to the root
- tag `v2.0.0` on the master branch
- submit the package to packagist: https://packagist.org/packages/submit

What do you think?

**Comment by bert-w** [comment]
i concur on all points.

**Comment by KyranRana** [comment]
@j0k3r All done! :)

**Comment by j0k3r** [comment]
Almost!

- You did not enable auto update on packagist. New release aren't shown on this page: https://packagist.org/packages/kyranrana/cloudflare-bypass
- I guess you should tag v2.0.1 on the current master with all these new changes: https://github.com/KyranRana/cloudflare-bypass/compare/v2.0.0...master

**Comment by KyranRana** [comment]
v3.0.0 out now.
