### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by L4BORG** [KyranRana/cloudflare-bypass#85]
I think latest commit has memory leak (I didn't test old ones).

I've been testing cURL example and memory usage would keep increasing if used in loop, even if I try to unset and set $curl_cf_wrapper in each iteration.

**Comment by L4BORG** [comment]
I take that back, I just saw it might be due to mistake on my end and unsetting $curl_cf_wrapper would actually fix the issue. Ill reopen if that's not the case.

**Comment by L4BORG** [comment]
After some more testing I can now confirm, when used in loop memory usage would constantly increase. Using cURL version with caching disabled.

**Comment by L4BORG** [comment]
Things I've tried so far:

- make sure to use curl_close($ch);
- unsetting $curl_cf_wrapper and creating new object for each request
- disabled cache

code used to test:

```
<?php

require 'autoload.php';

use CloudflareBypass\RequestMethod\CFCurl;

while(true)
{
	echo "Memory usage: ".memory_get_usage()." bytes\n";

	$curl_cf_wrapper = new CFCurl(array(
		'max_retries'   => 5,                   // How many times to try and get clearance?
		'cache'         => false,               // Enable caching?
		'cache_path'    => __DIR__ . '/cache',  // Where to cache cookies? (Default: system tmp directory)
		'verbose'       => false                 // Enable verbose? (Good for debugging issues - doesn't effect cURL handle)
	));

	// Get Example: 1
	$ch = curl_init("https://...");
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
	curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36');
	$data = $curl_cf_wrapper->exec($ch); // Done! NOTE: HEAD requests not supported!
	curl_close($ch);

	unset($curl_cf_wrapper);
	
	sleep(1);
}
```

output:

```
www-data@z220:~/_cloudflare$ php test.php
Memory usage: 351968 bytes
Memory usage: 586144 bytes
Memory usage: 715320 bytes
Memory usage: 845016 bytes
Memory usage: 974352 bytes
Memory usage: 1103368 bytes
Memory usage: 1232744 bytes
Memory usage: 1362720 bytes
Memory usage: 1492056 bytes
Memory usage: 1621232 bytes
Memory usage: 1750288 bytes
```

**Comment by L4BORG** [comment]
@KyranRana I think one of the issues is that $cf_request_method_copy is not being closed in CFBypasser.

The other thing I find strange is that memory usage increase after 

$cf_request_method->getPage();

but won't decrease after unsetting $response and calling $cf_request_method->close();

**Comment by L4BORG** [comment]
Also you're not closing handle in retention() in Storage.php but I don't think that's the issue since I'm not using Storage while testing.

**Comment by L4BORG** [comment]
I can confirm closing $cf_request_method_copy fixed the issue for me (I'm currently closing it before each return). With that only around 5kb-10kb of memory would be wasted for each loop.

**Comment by KyranRana** [comment]
Which version of PHP were you using?

**Comment by L4BORG** [comment]
System | Linux z220 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64
Build Date | Dec  7 2018 11:36:49
Server API | Apache 2.0 Handler

you think that could cause issues?

**Comment by L4BORG** [comment]
Forgot PHP version: PHP Version 7.0.33-0+deb9u1

**Comment by KyranRana** [comment]
I now close $cf_request_method_copy and I get the following logs from the above script:

Memory usage: 369264 bytes
Memory usage: 472280 bytes
Memory usage: 472280 bytes
Memory usage: 472280 bytes
Memory usage: 472280 bytes
Memory usage: 472280 bytes
Memory usage: 472280 bytes

**Comment by KyranRana** [comment]
You got telegram? Or any other messenger?

**Comment by L4BORG** [comment]
I have Telegram, what's your ID?

**Comment by KyranRana** [comment]
CoolioPD
