### ISSUE TITLE
500 error 

### ISSUE THREAD

**Issue by ash121121** [KyranRana/cloudflare-bypass#88]
Has V2 stopped working? Last few days I'm getting 500 server error.

Kind regards

**Comment by ash121121** [comment]
@j0k3r

**Comment by ash121121** [comment]
Fatal error: Uncaught ErrorException: Exceeded maximum retries trying to get CF clearance! in /usr/local/lsws/wordpress/libraries/bypass.php:423 Stack trace: #0 /usr/local/lsws/wordpress/libraries/bypass.php(426): CFCurl->exec(Object(Curl), false, 6) #1 /usr/local/lsws/wordpress/libraries/bypass.php(426): CFCurl->exec(Object(Curl), false, 5) #2 /usr/local/lsws/wordpress/libraries/bypass.php(426): CFCurl->exec(Object(Curl), false, 4) #3 /usr/local/lsws/wordpress/libraries/bypass.php(426): CFCurl->exec(Object(Curl), false, 3) #4 /usr/local/lsws/wordpress/libraries/bypass.php(426): CFCurl->exec(Object(Curl), false, 2) #5 /usr/local/lsws/wordpress/libraries/proxy.php(349): CFCurl->exec(Object(Curl)) #6 /usr/local/lsws/wordpress/index.php(225): proxy->forward_request('/', '191.64.119:...') #7 {main} thrown in /usr/local/lsws/wordpress/libraries/bypass.php on line 423

**Comment by KyranRana** [comment]
Are you using a proxy of some sort? I've tried with my CFBypass and its working fine.

**Comment by ash121121** [comment]
I'm using your class in my web proxy. All working fine till a week ago :(

**Comment by KyranRana** [comment]
Can I have your proxy ip? Or your full cURL code?

**Comment by ash121121** [comment]
I just tried your bypassed on a new server and your correct seems to work. No idea why mine and my friends suddenly stopped working. Any ideas much appreciated

**Comment by ash121121** [comment]
Fixed looks like i was using a old version.
