### ISSUE TITLE
V2 Version Problem 30/1/2019

### ISSUE THREAD

**Issue by minhhai27121994** [KyranRana/cloudflare-bypass#91]
I have problems with this library. Before few months ago, it still work, but now It's not working.
Please help me solve this problem.

require 'autoload.php';
curl_cf_wrapper = new CFCurl(array(
    'max_retries'   => 10,                   // How many times to try and get clearance?
    'cache'         => false,               // Enable caching?
    'cache_path'    => __DIR__ . '/cache',  // Where to cache cookies? (Default: system tmp directory)
    'verbose'       => true                 // Enable verbose? (Good for debugging issues - doesn't effect cURL handle)
));

// Get Example: 1
$ch = curl_init("https://bongngo.tv");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36');
echo $curl_cf_wrapper->exec($ch); // Done! NOTE: HEAD requests not supported!
curl_close($ch);

**Comment by snnyk** [comment]
yea v2 still not work

**Comment by KyranRana** [comment]
i'm going to take a look at this.

**Comment by KyranRana** [comment]
Update your master branch and try again. Let me know if you face any more 503s :)

**Comment by snnyk** [comment]
Fatal error: Call to undefined method CloudflareBypass\RequestMethod\Stream::close() in E:\wamp\www\cloudflare\src\CloudflareBypass\CFBypasser.php on line 207

and no any returned content

**Comment by KyranRana** [comment]
Can you paste me the code which runs the file_get_contents stuff?

**Comment by snnyk** [comment]
i just using test codes

**Comment by KyranRana** [comment]
Can you switch to the branch cloudflare-bypass-streamcontext-fix and try again? :)

Let me know if it works for you.

**Comment by snnyk** [comment]
yes its worked thx alot
