### ISSUE TITLE
Dangerous bug on cache storage manager - version 2.0.0

### ISSUE THREAD

**Issue by sabloger** [KyranRana/cloudflare-bypass#92]
Hi, I just replaced version 2.0.0 release files with old files, and got this warnings when i was trying to instantiate the CFCurl without cache_path option :

`Notice: Undefined index: cache_path in src/CloudflareBypass/CFCore.php on line 48

Warning: unlink(//var): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//opt): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//core): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//bin): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//lost+found): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//media): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//initrd.img): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//lib): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//snap): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//sbin): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//vmlinuz): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//lib64): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//cdrom): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//usr): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//boot): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//etc): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//vmlinuz.old): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//root): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//mnt): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//home): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//srv): Permission denied in src/CloudflareBypass/Storage.php on line 122

Warning: unlink(//initrd.img.old): Permission denied in src/CloudflareBypass/Storage.php on line 122`
There was a default value for null cache_path option on the old version, But it is deleted in the new version

**Comment by KyranRana** [comment]
Can you give me the full code? Also are you using the v2.0 release code or the old code? 

You confused me when you said you replaced new with old files.
