### ISSUE TITLE
cloudflare updated new version, can not get content

### ISSUE THREAD

**Issue by lilianorien** [KyranRana/cloudflare-bypass#95]
I think cloudflare updated new version , with more param s:
https://predb.me/cdn-cgi/l/chk_jschl?s=ac02ac0318b3917cd91a3ae004265455cf2f46cc-1553055008-1800-ARck+tk99tqKtxvgWDyIaPg5UjXquij3W3HtuB81I0moyznWipS72nWKxpZMUbZAQ3loSpzq2hBxTwxkjVIinCbMtyT4gijgxRva5htujP6n&jschl_vc=b19bb08b6b766c1cbb485d72e7b86691&pass=1553055012.407-YFSqwJtQKJ&jschl_answer=278.8951663557

Not only : chk_jschl?jschl_vc=c4b2b0ad0762c786db2902afecfea335&pass=1553054824.089-16uz5HOpMk&jschl_answer=25.4083790376 as before.

So content page can not get.

**Comment by neverknoww** [comment]
Yup, I can confirm this too. This is not working anymore.

ps. great script

**Comment by RootC** [comment]
Does anyone solve the problem ?

**Comment by KyranRana** [comment]
Update your master branch and try again. Let me know if any issues pop up. :)

**Comment by RootC** [comment]
thank you so much bless. KyranRana 👍

**Comment by neverknoww** [comment]
thank you very much

**Comment by yylzcom** [comment]
@neverknoww Do you manage to get this work?

I am getting this errer message witht the example:
` Exceeded maximum number of retries at getting cookie "cf_clearance" `

The version is the latest one:  " a302f72  "

**Comment by lilianorien** [comment]
Best script, thank you very much.
