### ISSUE TITLE
CloudFlare Update 20.03.2019 HTTP 500 Error

### ISSUE THREAD

**Issue by RootC** [KyranRana/cloudflare-bypass#96]
CloudFlare Update 20.03.2019 HTTP 500 Error ByPass  When Will the current version come ?

**Comment by KyranRana** [comment]
i'll take a look

**Comment by RootC** [comment]
Thank you l'm waiting

**Comment by lilianorien** [comment]
Many thanks.

**Comment by RootC** [comment]
is it gonna be okay ? KyranRana

**Comment by ash121121** [comment]
I hope there's a fix :(

**Comment by RootC** [comment]
I'm looking forward to it, I need it so much. :(

**Comment by KyranRana** [comment]
This is a big update they have made. I may need to add a JavaScript interpreter after all. I will keep you guys up to date.

**Comment by ash121121** [comment]
What do you mean by JavaScript interpretor.  Like phantom Js?

**Comment by RootC** [comment]
Thank you so much I'm waiting for good luck.

**Comment by KyranRana** [comment]
Which site does this error occur on? Like which site are you trying to access?

**Comment by RootC** [comment]
My Dude 

<?php
ini_set("display_errors","1");
header('Access-Control-Allow-Origin: *');
header("Content-type: application/json; charset=utf-8");


include 'src/autoload.php';

use CloudflareBypass\RequestMethod\CFCurl;
$curl_cf_wrapper = new CFCurl(array(
    'max_retries'   => 1,
    'cache'         => false,
    'cache_path'    => __DIR__ . '/cache',
    'verbose'       => false
));


$file 		= "cache/data.txt";
$adres 		= "https://www.bahissenin52.com";
$url 		= $adres.$_SERVER['REQUEST_URI'];


$ch 		= curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, true);
if($_POST) {
	curl_setopt($ch, CURLOPT_POSTFIELDS, $_POST);
}
if($_GET) {
	curl_setopt($ch, CURLOPT_POSTFIELDS, $_GET);
}
curl_setopt($ch, CURLOPT_COOKIEJAR, $file);
curl_setopt($ch, CURLOPT_COOKIEFILE, $file);
curl_setopt($ch, CURLOPT_REFERER,$adres);
curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.107');

echo $curl_cf_wrapper->exec($ch);
curl_close($ch);


I want to pull data from here that worked before now does not work.

you can look here.   http://api.betrunning98.com  
you'il see he made a mistake.

**Comment by ash121121** [comment]
https://eztv.io i tried here and get 500 error

**Comment by KyranRana** [comment]
Try the branch cloudflare-bypass-s-param and let me know if that works for you guys :)

**Comment by ash121121** [comment]
still 503 error for me :(

**Comment by ash121121** [comment]
Working now mate :D :D :D

**Comment by KyranRana** [comment]
Merged changes into master. Let me know if this issue pops up again.
