### ISSUE TITLE
Attention Required! | Cloudflare  Please enable cookies

### ISSUE THREAD

**Issue by RootC** [KyranRana/cloudflare-bypass#98]
Hello Dude

` <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error"id="cookie-alert"data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details"class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1data-translate="challenge_headline">One more step</h1>
        <h2class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to access</span> www.betlima110.com</h2>
      </div>
      
      <div class="cf-section cf-highlight cf-captcha-container">
        <div class="cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">
            
              <div class="cf-highlight-inverse cf-form-stacked">
                <form class="challenge-form"id="challenge-form"action="/cdn-cgi/l/chk_captcha"method="get">
  <input type="hidden"name="s"value="57b2b30936e1e0d86e9b465d5a01a5a74be3b053-1553341613-1800-AX8CaQYdnqkgw/WSJO26WV+q7Fh4pAP/Bui+kzRpcxu7AuVv3DrXT2cuAiXrFkNu9zWKP4RNf0wYeHWWhcJE04YcZIQF10t/DwACSwoTf9u35f+4JnR3tl6hUiusb/e+kg=="></input>
  <script type="text/javascript"src="/cdn-cgi/scripts/cf.challenge.js"data-type="normal"data-ray="4bc02ada4eb4b7cb"async data-sitekey="6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0"></script>
  <div class="g-recaptcha"></div>
  <noscript id="cf-captcha-bookmark"class="cf-captcha-info">
    <div><div style="width: 302px">
      <div>
        <iframe src="https://www.google.com/recaptcha/api/fallback?k=6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0"frameborder="0"scrolling="no"style="width: 302px; height:422px; border-style: none;"></iframe>
      </div>
      <div style="width: 300px; border-style: none; bottom: 12px; left: 25px; margin: 0px; padding: 0px; right: 25px; background: #f9f9f9; border: 1px solid #c1c1c1; border-radius: 3px;">
        <textarea id="g-recaptcha-response"name="g-recaptcha-response"class="g-recaptcha-response"style="width: 250px; height: 40px; border: 1px solid #c1c1c1; margin: 10px 25px; padding: 0px; resize: none;"></textarea>
        <input type="submit"value="Submit"></input>
      </div>
    </div></div>
  </noscript>
</form>

                
              </div>
            </div>

            <div class="cf-column">
              <div class="cf-screenshot-container">
              
                <span class="cf-no-screenshot"></span>
              
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>
            
            <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
          </div>`

I can't get past this problem.  ? :S

**Comment by KyranRana** [comment]
You need to use a proxy if that happens. Change your IP and let me know if that fixes the problem for you.

**Comment by RootC** [comment]
`<?php
ini_set("display_errors","0");
header('Access-Control-Allow-Origin: *');
header("Content-type: application/json; charset=utf-8");


include 'src/autoload.php';

use CloudflareBypass\RequestMethod\CFCurl;
$curl_cf_wrapper = new CFCurl(array(
    'max_retries'   => 1,
    'cache'         => false,
    'cache_path'    => __DIR__ . '/cache',
    'verbose'       => false
));


$file 		= "cache/data.txt";
$adres 		= "https://www.bahissenin52.com";
$url 		= $adres.$_SERVER['REQUEST_URI'];


$ch 		= curl_init();
curl_setopt($ch, CURLOPT_PROXY, '78.187.228.9:8080');
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, true);
if($_POST) {
	curl_setopt($ch, CURLOPT_POSTFIELDS, $_POST);
}
if($_GET) {
	curl_setopt($ch, CURLOPT_POSTFIELDS, $_GET);
}
curl_setopt($ch, CURLOPT_COOKIEJAR, $file);
curl_setopt($ch, CURLOPT_COOKIEFILE, $file);
curl_setopt($ch, CURLOPT_REFERER,$adres);
curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36');

echo $curl_cf_wrapper->exec($ch);
curl_close($ch);
`

in any way does not work.

I've tried different servers in different countries.

**Comment by KyranRana** [comment]
Cloudflare loves to blacklist a lot of the proxy ips, you need to keep trying :)

I've used my IP and it works fine. Have you tried your own IP?

**Comment by RootC** [comment]
I bought 100 different IP addresses. I've tried it all, it doesn't work.

ASN is issuing the Forbidden cloudflare line.

and most of them please enable cookies. he's making his mistake.

**Comment by RootC** [comment]
Before the update came, I was using a single IP address conveniently. now, unfortunately, he's making a mistake.

**Comment by KyranRana** [comment]
Do you have teamviewer or join.me? Add me on telegram @CoolioPD
