### ISSUE TITLE
Exceeded maximum number of retries at getting cookie

### ISSUE THREAD

**Issue by yylzcom** [KyranRana/cloudflare-bypass#99]
Hi,

After this update I got the errors like this:
`Exceeded maximum number of retries at getting cookie "cf_clearance". in /var/www/fetch/vendor/kyranrana/cloudflare-bypass/src/CloudflareBypass/CFBypasser.`

I tried my own code and the example code but all failed like above. Any suggestion or advice?

Best regards!

**Comment by KyranRana** [comment]
Can you do me a favour? To debug this problem:

1. Open Incognito Google Chrome.
2. Right click and click inspect.
3. Click the network tab.
4. Tick the "preserve log" tick box.
5. Go to the site which is protected by CF page.
6. Click on the first row which pops up in the network tab.
7. Click on the response tab and copy the HTML here.

**Comment by yylzcom** [comment]
Hi,

I try the url in the example code, wich is `https://predb.me/?search=720p`

The first row returns a 503 error and the respons tab is empty.

The second row is fav.ico, which I guess is not helpful.

The third row is the url, which the response tab is empty too: 
`https://predb.me/cdn-cgi/l/chk_jschl?s=479eff159ca538229ecdaf88aa7d9d226f5de618-1553346714-1800-AfAyFC4wukaYIbhkPdQF1zeUJimVgSENMt7XCrhwGRzQXN0ksGsccyxKVe2Du06KmSOT4OhY50L7CcVipGIu6cPqSXsOJu32pMPXVEfRZ%2FwK4JDB9nfwLW5HwwJCBGwZjIPE87B%2BqvNek1L1CBfU42g%3D&jschl_vc=42c679d5c36fcc6e40ea15d673f7c5b1&pass=1553346718.652-Ihve%2Be03vv&jschl_answer=13.1589069271`

**Comment by KyranRana** [comment]
Add me on telegram @CoolioPD and I'll help you debug this problem :)

**Comment by yylzcom** [comment]
Thanks and the problem fix.

Close this issue for now.
